### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by leejjoon** [IGRINScontact/RRISA#3]
Some of the URLS seems to be broken.

For example,  the file `20170501/SDCH_20170501_0095.spec.fits`
has a url of 'https://utexas.box.com/shared/static/nwl1e38n016s84plo933zdhax01srvhr.fits' (from RRISA_XMatch/xmatch_log.csv), but when I visit the link, it says the link is removed.

It is not just this file, there are bunch of files that are not accessible. For some of them, I checked that they can be downloaded if I manually log in to the box page from the browser.

My guess is that these urls are accessible for only a finite amount of time and then expire after that?

**Comment by ericasaw** [comment]
We are aware of the temporary link issue and are working to fix it with Box Support. Until then, the individual download links for reduced files will not work (and more will continue to expire). We will update and resolve this issue when the permanent links are generated.

**Comment by ericasaw** [comment]
Hi @leejjoon,
The links have been updated in the archive so now they will all be permanently available. Let me know if you run into any issues!
